RivetMC_QCDAWARE_JETS.so: QCDAWAREJETS.cc FinalPartons.cc FinalPartons.hh UserInfoParticle.hh
	rivet-buildplugin RivetMC_QCDAWARE_JETS.so QCDAWAREJETS.cc FinalPartons.cc `fastjet-config --prefix`/lib/libQCDAware.a

